Ecommerce/Areas/User/Controllers/MainPageController.cs
using AutoMapper;
using Data.Unit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using ModelsDTO.DTO.MainPageControllerDTO;
using Services.Autenticacao;
using Services.Favorites;

namespace EcommerceWeb.Areas.User.Controllers
{
    [Area("User")]
    //[BindProperties]
    public class MainPageController : Controller
    {
        public IUnitOfWork _db;
        private readonly IMapper _mapper;


		public MainPageController(IUnitOfWork db,IMapper mapper)
        {
            _db = db; 
            _mapper = mapper;
        }


        #region Index
        public IActionResult Index()
        {
            var FinalModel = new MainPageDTO();
            Account? user = new Autenticacao(_db).GettingUser();

            if(user == null)
            {
                FinalModel.conta = null;
            }
            else
            {
                FinalModel.conta = user;
            }

            FinalModel.produto = _db.Produto.GetAll();


            return View(FinalModel);
        }

        #endregion

        #region Insert

        
        public IActionResult Insert()
        {   
            IEnumerable<SelectListItem> categories = _db.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Produto prod)
        {
            Account conta = new Autenticacao(_db).GettingUser();
            if (conta.Role != Models.Enums.Roles.Administrator)
                return RedirectToAction("Index");
            
            else if (prod == null)
                return View();

            else
            {
                _mapper.Map<ProdutoDTO>(prod);
                prod.Id = 0; 
				_db.Produto.Insert(prod);
                return RedirectToAction("Index");
            }
			// o entity framework estava lançando um valor default de 1 para o Id mesmo com o IDENTITY_INSERT Produto ON no sql
			//entao a solução é manualmente mudar o ID para 0 que fará com que o SQL lide com o valor do Id sozinho (simples auto increment no caso).
		}

		#endregion

		#region Details
		public IActionResult Details(int id)
        {
            Produto prod = new Produto();
            prod = _db.Produto.GetById(c => c.Id == id);
            DetailsDTO model = new DetailsDTO(_db)
            { 
                produto = prod
            };
            model.AccountAndCategory();
            return View(model);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            Account conta = new Autenticacao(_db).GettingUser();
            if(conta.Role != Models.Enums.Roles.Administrator)
            {
                return RedirectToAction("Index");
            }


            string? categoria;
            var produto = _db.Produto.GetById(c => c.Id == id);
            if (produto.CategoriaId == null)
                categoria = "Sem Categoria";
            else
                categoria = _db.Category.GetById(c => c.Id == produto.CategoriaId).Name;


            IEnumerable<SelectListItem> categories = _db.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });

            ViewBag.Categories = categories;
            ViewData["categoria"] = categoria;
            return View(produto);
        }

        [HttpPost]
        public IActionResult Edit(Produto produto)
        {
            Account conta = new Autenticacao(_db).GettingUser();
            if (conta.Role != Models.Enums.Roles.Administrator)
                return RedirectToAction("Index");
            else
            {
                _db.Produto.Edit(produto);
                return RedirectToAction("Index");
            }
        }

        #endregion

        #region Delete


        public IActionResult Delete(int id)
        {
            var produto =_db.Produto.GetById(c => c.Id == id);
            return View(produto);
        }

        [HttpPost]
        public IActionResult Delete(Produto produto)
        {
            Account conta = new Autenticacao(_db).GettingUser();
            if (conta.Role != Models.Enums.Roles.Administrator)
            {
                return RedirectToAction("Index");
            }
            _db.Produto.Delete(produto);
            return RedirectToAction("Index");
        }

        #endregion

        #region FavoritosRegion

        
        public IActionResult Favorites(int id)
        {
			ViewData["acao"] = "";
			Account conta = new Autenticacao(_db).GettingUser();
			Produto prod = _db.Produto.GetById(c => c.Id == id);
            FavoritosFunctionalities favfunc = new FavoritosFunctionalities(_db,conta);
			Favoritos? registro = _db.Favoritos.FindFavoriteRegister(conta, prod);
			
            if (registro == null)
			    ViewData["acao"] = "Adicionar";
			else
			    ViewData["acao"] = "Deletar";

			return View(prod);
        }


        [HttpPost]
        public IActionResult FavoritesPost(int id)
        {
            Account conta = new Autenticacao(_db).GettingUser();
            Produto prod = _db.Produto.GetById(c => c.Id == id);
            FavoritosFunctionalities favs = new FavoritosFunctionalities(_db,conta);
            Favoritos? registro =_db.Favoritos.FindFavoriteRegister(conta, prod);
            if (registro == null)
            {
                _db.Favoritos.InsertAFavorite(conta, prod);
                return RedirectToAction("Index");  
            }
            else
            {
                _db.Favoritos.Delete(registro);
                return RedirectToAction("Index");
            }
        }


        #endregion
    }

}

Ecommerce/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    @*
    <link rel="stylesheet" href="~/css/reset.css" asp-append-version="true" />

    *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/BootstrapTheme.css" />
    <link rel="stylesheet" href="~/css/MainPage/Index.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">


    
    <!-- Option 1: Include in HTML -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black text-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="User" asp-controller="MainPage" asp-action="Index">Página principal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="MainPage" asp-action="Index">Home</a>
                        </li>
                        *@
                        
                    </ul>
                </div>
                    <button class="btn">
                    <a class="text-lg-center" asp-area="User" asp-controller="Account" asp-action="Index">
                        <i class="bi bi-person-circle text-white display-6 "></i>
                        </a>
                    </button>
@*
                // leaving that as comented cz it is not well implemented yet
                <button id="NightOrDay" class="btn btn-dark text-lg"><i class="bi bi-moon-stars"></i></button>
*@
            </div>
            
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>